In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('india_road_accident.csv')
df

Year          State Urban_Rural Road_Type Weather Vehicle_Type  \
0     2021         Odisha       Rural        SH   Rainy  Two-Wheeler   
1     2021          Delhi       Rural     Rural     Fog        Truck   
2     2021          Bihar       Urban        NH     Fog  Two-Wheeler   
3     2023   Chhattisgarh       Rural     Rural   Rainy          Car   
4     2014         Punjab       Urban     Rural   Clear          Bus   
...    ...            ...         ...       ...     ...          ...   
8195  2010   Chhattisgarh       Rural        NH     Fog          Car   
8196  2010   Chhattisgarh       Rural      City   Clear          Car   
8197  2015          Delhi       Rural     Rural   Rainy          Bus   
8198  2022         Kerala       Rural        NH   Rainy  Two-Wheeler   
8199  2022  Uttar Pradesh       Rural     Rural   Clear  Two-Wheeler   

      Accident_Count  Fatalities  Injuries  Severity_Index  
0              22984        3087     12784            5.78  
1              10514         762      5853            7.52  
2               9162         760      3797            8.72  
3              12100        1549      6145            8.37  
4              19805        2812     11478            9.10  
...              ...         ...       ...             ...  
8195           15207        2256     10450            5.13  
8196           13286         943      9861            5.82  
8197           18692        1148     11594            6.76  
8198            6895         971      4660            8.52  
8199           23945        2232     15420            7.40  

[8200 rows x 10 columns]

In [2]:
df.shape

(8200, 10)

In [3]:
df.columns

Index(['Year', 'State', 'Urban_Rural', 'Road_Type', 'Weather', 'Vehicle_Type',
       'Accident_Count', 'Fatalities', 'Injuries', 'Severity_Index'],
      dtype='object')

In [4]:
df.head()

Year         State Urban_Rural Road_Type Weather Vehicle_Type  \
0  2021        Odisha       Rural        SH   Rainy  Two-Wheeler   
1  2021         Delhi       Rural     Rural     Fog        Truck   
2  2021         Bihar       Urban        NH     Fog  Two-Wheeler   
3  2023  Chhattisgarh       Rural     Rural   Rainy          Car   
4  2014        Punjab       Urban     Rural   Clear          Bus   

   Accident_Count  Fatalities  Injuries  Severity_Index  
0           22984        3087     12784            5.78  
1           10514         762      5853            7.52  
2            9162         760      3797            8.72  
3           12100        1549      6145            8.37  
4           19805        2812     11478            9.10

In [5]:
df.tail()

Year          State Urban_Rural Road_Type Weather Vehicle_Type  \
8195  2010   Chhattisgarh       Rural        NH     Fog          Car   
8196  2010   Chhattisgarh       Rural      City   Clear          Car   
8197  2015          Delhi       Rural     Rural   Rainy          Bus   
8198  2022         Kerala       Rural        NH   Rainy  Two-Wheeler   
8199  2022  Uttar Pradesh       Rural     Rural   Clear  Two-Wheeler   

      Accident_Count  Fatalities  Injuries  Severity_Index  
8195           15207        2256     10450            5.13  
8196           13286         943      9861            5.82  
8197           18692        1148     11594            6.76  
8198            6895         971      4660            8.52  
8199           23945        2232     15420            7.40

In [6]:
df.dtypes

Year                int64
State              object
Urban_Rural        object
Road_Type          object
Weather            object
Vehicle_Type       object
Accident_Count      int64
Fatalities          int64
Injuries            int64
Severity_Index    float64
dtype: object

In [7]:
df.isna().sum()

Year              0
State             0
Urban_Rural       0
Road_Type         0
Weather           0
Vehicle_Type      0
Accident_Count    0
Fatalities        0
Injuries          0
Severity_Index    0
dtype: int64

In [8]:
categorical_cols = ['State','Urban_Rural','Road_Type','Weather','Vehicle_Type']



In [9]:
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [10]:
df

Year  Accident_Count  Fatalities  Injuries  Severity_Index  \
0     2021           22984        3087     12784            5.78   
1     2021           10514         762      5853            7.52   
2     2021            9162         760      3797            8.72   
3     2023           12100        1549      6145            8.37   
4     2014           19805        2812     11478            9.10   
...    ...             ...         ...       ...             ...   
8195  2010           15207        2256     10450            5.13   
8196  2010           13286         943      9861            5.82   
8197  2015           18692        1148     11594            6.76   
8198  2022            6895         971      4660            8.52   
8199  2022           23945        2232     15420            7.40   

      State_Arunachal Pradesh  State_Assam  State_Bihar  State_Chhattisgarh  \
0                       False        False        False               False   
1                       False        False        False               False   
2                       False        False         True               False   
3                       False        False        False                True   
4                       False        False        False               False   
...                       ...          ...          ...                 ...   
8195                    False        False        False                True   
8196                    False        False        False                True   
8197                    False        False        False               False   
8198                    False        False        False               False   
8199                    False        False        False               False   

      State_Delhi  ...  State_West Bengal  Urban_Rural_Urban  Road_Type_NH  \
0           False  ...              False              False         False   
1            True  ...              False              False         False   
2           False  ...              False               True          True   
3           False  ...              False              False         False   
4           False  ...              False               True         False   
...           ...  ...                ...                ...           ...   
8195        False  ...              False              False          True   
8196        False  ...              False              False         False   
8197         True  ...              False              False         False   
8198        False  ...              False              False          True   
8199        False  ...              False              False         False   

      Road_Type_Rural  Road_Type_SH  Weather_Fog  Weather_Rainy  \
0               False          True        False           True   
1                True         False         True          False   
2               False         False         True          False   
3                True         False        False           True   
4                True         False        False          False   
...               ...           ...          ...            ...   
8195            False         False         True          False   
8196            False         False        False          False   
8197             True         False        False           True   
8198            False         False        False           True   
8199             True         False        False          False   

      Vehicle_Type_Car  Vehicle_Type_Truck  Vehicle_Type_Two-Wheeler  
0                False               False                      True  
1                False                True                     False  
2                False               False                      True  
3                 True               False                     False  
4                False               False                     False  
...                ...                 ...                       ...  
8

In [11]:
df.dtypes

Year                          int64
Accident_Count                int64
Fatalities                    int64
Injuries                      int64
Severity_Index              float64
State_Arunachal Pradesh        bool
State_Assam                    bool
State_Bihar                    bool
State_Chhattisgarh             bool
State_Delhi                    bool
State_Goa                      bool
State_Gujarat                  bool
State_Haryana                  bool
State_Himachal Pradesh         bool
State_Jharkhand                bool
State_Karnataka                bool
State_Kerala                   bool
State_Madhya Pradesh           bool
State_Maharashtra              bool
State_Odisha                   bool
State_Punjab                   bool
State_Rajasthan                bool
State_Tamil Nadu               bool
State_Telangana                bool
State_Uttar Pradesh            bool
State_Uttarakhand              bool
State_West Bengal              bool
Urban_Rural_Urban           

In [12]:
df.shape

(8200, 36)

In [13]:
x = df.drop(columns=['Accident_Count']).values
y= df['Accident_Count'].values
x

array([[2021, 3087, 12784, ..., False, False, True],
       [2021, 762, 5853, ..., False, True, False],
       [2021, 760, 3797, ..., False, False, True],
       ...,
       [2015, 1148, 11594, ..., False, False, False],
       [2022, 971, 4660, ..., False, False, True],
       [2022, 2232, 15420, ..., False, False, True]],
      shape=(8200, 35), dtype=object)

In [14]:
y

array([22984, 10514,  9162, ..., 18692,  6895, 23945], shape=(8200,))

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[2016, 1002, 6176, ..., False, False, True],
       [2015, 994, 8113, ..., False, False, True],
       [2022, 2915, 12302, ..., False, True, False],
       ...,
       [2012, 829, 6805, ..., True, False, False],
       [2018, 1317, 9638, ..., False, False, False],
       [2019, 118, 636, ..., False, False, False]],
      shape=(5740, 35), dtype=object)

In [16]:
x_test

array([[2010, 1124, 7500, ..., False, False, False],
       [2012, 65, 695, ..., False, False, True],
       [2020, 3089, 8990, ..., False, False, False],
       ...,
       [2013, 1999, 11661, ..., False, False, True],
       [2011, 133, 521, ..., False, True, False],
       [2024, 2866, 12820, ..., False, True, False]],
      shape=(2460, 35), dtype=object)

In [17]:
y_train

array([14378, 10567, 24997, ..., 11775, 21868,   887], shape=(5740,))

In [18]:
y_test

array([10135,   957, 21980, ..., 22892,   934, 24089], shape=(2460,))

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [20]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([11896.30600653,  2102.19502166, 18781.90743712, ...,
       18755.68147753,  2460.02506613, 22548.9313239 ], shape=(2460,))

In [21]:
y_test

array([10135,   957, 21980, ..., 22892,   934, 24089], shape=(2460,))

In [22]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


In [23]:
score=r2_score(y_test,y_pred)*100
score

89.33727192084827